# Generated by Django 5.2.8 on 2025-12-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("member_registering_page", "0001_initial"),
        ("room_registering_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("access", "Access"),
                            ("denied", "Denied"),
                        ],
                        default="access",
                        max_length=20,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="room_registering_page.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_activities",
                        to="member_registering_page.memberrecord",
                    ),
                ),
            ],
            options={
                "db_table": "room_activity",
                "ordering": ["-time"],
            },
        ),
    ]
