# Generated by Django 5.2.8 on 2025-12-05 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member_registering_page", "0001_initial"),
        ("room_activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomactivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_activities",
                to="member_registering_page.memberrecord",
            ),
        ),
    ]
