# Generated by Django 5.2 on 2025-10-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.PositiveIntegerField(blank=True, null=True)),
                ('buttons', models.JSONField(default=[1, 1, 1, 1, 1, 1])),
                ('audio1', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('audio2', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('audio3', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member Record',
                'verbose_name_plural': 'Member Records',
                'db_table': 'member_record',
            },
        ),
    ]
