# Generated by Django 5.0.9 on 2025-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_registering_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='audio1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='audio2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='audio3',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
