# Generated by Django 5.0.9 on 2025-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_registering_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.PositiveIntegerField(blank=True, help_text='Enter the room ID (positive integer).', null=True)),
                ('buttons', models.JSONField()),
                ('audio1', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('audio2', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('audio3', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ButtonState',
        ),
    ]
