# Generated by Django 5.0.9 on 2025-10-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_registering_page', '0002_memberrecord_delete_buttonstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberrecord',
            options={'verbose_name': 'Member Record', 'verbose_name_plural': 'Member Records'},
        ),
        migrations.AlterModelTable(
            name='memberrecord',
            table='member_record',
        ),
    ]
