# Generated by Django 4.2.7 on 2025-11-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_registering_page', '0002_alter_memberrecord_audio1_alter_memberrecord_audio2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
