# Generated by Django 5.0.9 on 2025-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_registering_page', '0003_alter_memberrecord_options_alter_memberrecord_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='room',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
