# Generated by Django 4.2.7 on 2025-11-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_registering_page', '__first__'),
        ('member_registering_page', '0003_memberrecord_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='room_registering_page.room'),
        ),
    ]
