# Generated by Django 5.2.8 on 2025-11-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_registering_page', '0004_alter_memberrecord_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecord',
            name='room',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
