# Generated by Django 5.0.9 on 2025-10-28 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_registering_page', '0002_memberrecord_delete_buttonstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Room name must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=50)),
                ('total_members', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to='member_registering_page.memberrecord')),
            ],
        ),
    ]
