# Generated by Django 5.0.9 on 2025-10-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_registering_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Room'},
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
