# Generated by Django 5.0.9 on 2025-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_registering_page', '0002_alter_room_options_alter_room_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='total_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
